CREATE TABLE IF NOT EXISTS `#_greetings` (
    `id` INT(11) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    `name` VARCHAR(255) NOT NULL,
    `detail` TEXT,
    `created` TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);